### ISSUE TITLE
CSV Issues: Career and Technical Education - Arkansas Department of CorrectionsAR DEPT CORRECTIONS_WHITEInfo

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/ai-course-crawler#20]
The Arkansas Department of Corrections CSV file has the following issues.
https://master.ai-course-crawler.development.c66.me/datasets/catalogue/4

The information below is applicable to all of the courses with this data set. 

See the bulk upload templates for the correct head rows:
[Bulk Upload Template with Every Property](https://docs.google.com/spreadsheets/d/182TnqnwLzbw0ETIxV2U0KcMvRPqD1q2jwQksNYc4gPo/edit?usp=sharing)

[Bulk Upload Template with Ivy Tech example](https://docs.google.com/spreadsheets/d/1o50bQ7rhqc1m38a-ZYZBEjz7MQDMt6MiDyQIwvQn2MI/edit?gid=920458360#gid=920458360)

The **Program Descrition** is for the Program that offers the courses, not the courses.  The coursese are listed under **Program Courses**.  In the example, below, there's two courses (1) Financial Literacy  and (2) Agricultural Equipment Technician.

**OTHER ISSUES**
1. The catalog does not have course numbers.  It used the course name as the identifier.  This may be alright.  We need to discuss this. 
2. The "Type" column is missing.  Every course bulk upload file must have a "Type" column. For courses, the type will always = Course.
3. The column headings are not correct

- Don't  use course_id, use External Identifier
- Don't use course_name, use Learning Opportunity Name
- Don't use couse_description, use Description
- Don't use course_credits_min, use ConditionProfile: Credit Unit Value 
- It is incorrect to include the course_credits_max.  

**REQUIRED COLUMNS FOR ALL COURSES**See the minimum data policy for Course https://credreg.net/registry/policy#course

- Learning Opportunity Name = Course  (e.g., Financial Literacy)
- Description = Use the description that is commonly used or already available on your website. (e.g., Learn about creating a budget, banking services and the basics of borrowing money.)
- External Identifier = The Course number. If there  isn't a course number, we need to make sure the course names are unique to use them as an identifier.  Not that with the bulk upload, a CTID is not required, the system will mint the CTID for each course. (e.g., Financial Literacy)
- Language = English 
- Life Cycle Status Type = Active
- In Catalog = URL for the course catalog page or URL for the Course. (e.g., https://doc.arkansas.gov/correctional-school-district/riverside-vo-tech/)

**EXPECTED**
- 
- Credit Unit Value = Enter number of either credit units awarded for college credit or continuing education units for successful completion of the learning opportunity or assessment. (e.g. for Financial Literacy the Credit Unit Value = 10
- Credit Unity Type = Contact Hour (https://credreg.net/ctdl/terms/lifeCycleStatusType#CreditUnit)
- ConditionProfile: Description = Entrance Requirmenets (e.g., Must be a farm worker at the Cummins Unit to be eligible for this program.)

![image](https://github.com/user-attachments/assets/559bb4f4-5c59-45cb-89a1-c89d96e216ff)

**Comment by rsaksida** [comment]
Closing this in favor of tracking all the supported fields via #43.
