### ISSUE TITLE
Incorrect Header Row for Thomas Edison Community College Course CSV

### ISSUE THREAD

**Issue by rvilsack** [CredentialEngine/ai-course-crawler#27]
The Thomas Edison Community College CSV file has the following issues.

- Incorrect header row for Subject Webpage. Header Row provided in CVS extract=In Catalog 

AI Course Crawler Extract link: https://master.ai-course-crawler.development.c66.me/extractions/13

Extract file in Google Sheets with comparison to expected: https://docs.google.com/spreadsheets/d/1TEwPDD3xVGZrNi1G-9-KqS9muhox9gkCEMg9bjWvIy4/edit?usp=sharing 

The information below is applicable to all of the courses with this data set.

OTHER ISSUES

Assumption that the Credit Unit Type=Semester Hours

EXPECTED
Subject Webpage as header row instead of "In Catalog"

**Comment by edgarf** [comment]
According to @rvilsack, I will close this issue.
