### ISSUE TITLE
Complete Extraction for Michigan Virtual with no course file

### ISSUE THREAD

**Issue by rvilsack** [CredentialEngine/ai-course-crawler#29]
URL tested: https://michiganvirtual.org/courses/professional/
Crawler extraction link: https://master.ai-course-crawler.development.c66.me/extractions/10 

Extraction finished but no courses were provided:
 ![image](https://github.com/user-attachments/assets/771356d2-84c8-4dc6-be54-9f911ecefe68)

**Comment by rsaksida** [comment]
The problem here is in the recipe. The model is getting confused when detecting pagination. 

I'll add some additional checks to prevent this type of error, but #40 should help as well.
