### ISSUE TITLE
Complete Extraction for Bunker Hill Community College with no course file

### ISSUE THREAD

**Issue by rvilsack** [CredentialEngine/ai-course-crawler#30]
URL tested: https://catalog.bhcc.edu/content.php?catoid=10&navoid=485 
Crawler extraction list: https://master.ai-course-crawler.development.c66.me/extractions/14 

Extract finished on a course URL page that I would have expected course extracts:
![image](https://github.com/user-attachments/assets/3948c089-0f5d-46d5-87ad-0a6cecc68f15)

**Comment by rsaksida** [comment]
The issue was in the recipe. I've deployed a couple of updates to the recipe configuration detection that seem to have fixed it. An extraction is running right now.
