### ISSUE TITLE
Unexpected Data in Extract for Forsyth Tech

### ISSUE THREAD

**Issue by rvilsack** [CredentialEngine/ai-course-crawler#32]
The Forsyth Tech Bulk Upload file has the following issues.

AI Course Crawler Extract link: https://master.ai-course-crawler.development.c66.me/datasets/courses/16

Extract file in Google Sheets with comparison to expected: https://docs.google.com/spreadsheets/d/1z-8mCAYKzjELVCfZEmTBA4AkBDRxLlmwFTveLIWVh-I/edit?usp=sharing

The information below is applicable to the majority of courses with this data set.

ALL ISSUES

- Unexpected data that is not on URL provided to Course Crawler, including credentials and personal enrichment programs
- Missing Prerequites and Corequisites for course (should be a Condition Profile format)
- Credit Type assumed to be Semester Credit (see https://github.com/CredentialEngine/ai-course-crawler/issues/31)
- Data download has ANSI UTF-8 text encoding issues with export to Excel
See:
![Screenshot 2024-08-23 121716](https://github.com/user-attachments/assets/407944e7-a95d-4480-b06f-7bf45688795b)

EXPECTED, see highlighted row in the "Comparison to Correct Bulk Upload" tab in this [spreadsheet](https://docs.google.com/spreadsheets/d/1z-8mCAYKzjELVCfZEmTBA4AkBDRxLlmwFTveLIWVh-I/edit?usp=sharing)

Rows 2-15 and 25-54 - these are not courses listed on the URL provided
![Screenshot 2024-08-23 122927](https://github.com/user-attachments/assets/80dbd7f4-2886-486a-ba61-ae14cb3562a3)

Row 18  "Improving Study Skills"- all course data is extracted correctly; credit unit type is set to SemesterHour when the URL just lists "Credit". 

Here is what was listed for this course in the URL provided to the crawler:
![Screenshot 2024-08-23 122639](https://github.com/user-attachments/assets/44b42189-0e97-48fc-bc04-1463ec8d4607)

Also prerequisites and corequisites are included on URL but not in extract. Could have extracted the following Header Rows: 
Condition Profile: Condition Type = Requires
Condition Profile: Name =The following is required before taking this course
Condition Profile: Description = None

Condition Profile: Condition Type = Corequisite
Condition Profile: Name = The following is required to be taken with this course
Condition Profile: Description = None

(This example listed None for requirements and corequisites; other courses had additional data.)

**Comment by edgarf** [comment]
@rsaksida  - For purposes to release something MVP, let's concentrate on the main fields only, and then when we are sure about the rest of the functionality, let's do things like prerequisites, corequisites, credit-type and other additional fields.
