### ISSUE TITLE
Mismatched encoding with UTF-8 characters in bulk download when viewed in Excel

### ISSUE THREAD

**Issue by jeff-grann** [CredentialEngine/ai-course-crawler#35]
Example in crawler:
Ivy Tech Data Library
https://master.ai-course-crawler.development.c66.me/datasets/courses/1
Course
44 | ABRK 215 | OSHA 10 Certification | This course provides a study of the US Occupational Safety and Health Administration’s (OSHA) regulations that pertain to protecting workers from exposure to occupational hazards.

In Excel:
![Screenshot 2024-08-26 121530](https://github.com/user-attachments/assets/a10ace79-cddf-4071-8c6a-e52ce9d647b4)

**Comment by rsaksida** [comment]
The bulk-upload template is meant to be consumed by an API service, so the file isn't optimize for displaying on Excel.
In my experience, tailoring a CSV for Excel display may break the CSV for other tools, and vice-versa.
So for the CSV export, I think we should make sure it works with the API service first. For Excel, we can build a XLSX export as an additional feature (I'll bring this up in the next call).
