### ISSUE TITLE
Bergen catalog extraction failed

### ISSUE THREAD

**Issue by jeff-grann** [CredentialEngine/ai-course-crawler#37]
Recipe configuration detection #46 has failed.

AI Course Crawler failed to detect a valid configuration for this recipe.

You can adjust the URL, or try again.

Failure reason:
Timeout hit: 30000
![image](https://github.com/user-attachments/assets/39d9beca-c20e-4b79-ba7e-94341c4bea2d)

**Comment by rsaksida** [comment]
Sometimes configuration detection fails for various reasons (high load on the server, our server getting rate limited, connectivity issues with the website, etc). As the message points out, it is possible to retry the detection. Running it now, it was able to complete successfully.
