### ISSUE TITLE
Baruch College CUNY: Recipe configuration detection #64 has failed

### ISSUE THREAD

**Issue by jeannekitchens** [CredentialEngine/ai-course-crawler#46]
@rsaksida this college is flagged as "supported" with the course tracking sheet https://docs.google.com/spreadsheets/d/1qW5k0X9TlO4qU87QvNvG-gXFmAeMgGwLK2G5b5GWMN4/edit?gid=0#gid=0.  

The correct URL was used https://baruch-undergraduate.catalog.cuny.edu/courses. 

Per the email sent, pasted below,

![image](https://github.com/user-attachments/assets/2b6a6a59-e713-44dc-803c-a4872a2b0db5)

https://master.ai-course-crawler.development.c66.me/catalogues/28/recipes/64

Configuration Error

AI Course Crawler failed to detect a valid configuration for this recipe.

You can adjust the URL, or try again.

Failure reason:

Could not find every example

**Comment by rsaksida** [comment]
@jeannekitchens Reviewing that page now, I think assigning it to "Supported" was a bad call. The URL structure matches what we do perfectly, but the way the page loads courses via JavaScript makes it tricky to extract the catalogue without building in support for that specific page. It fetches courses with an API request that is initiated after the API is loaded, and they don't prerender the courses in the HTML.

So this is a case where would need to build specific support for the catalogue. I defer to you guys to decide whether and when we should pursue that.

**Comment by jeannekitchens** [comment]
Ok.  we should not prioritize it now. I'll change it to unsupported.
